"""add options to exercise column

Revision ID: 24d19ecfaebc
Revises: ae28da3082cd
Create Date: 2026-10-08 10:58:35.303819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d19ecfaebc'
down_revision: Union[str, Sequence[str], None] = 'ae28da3082cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'options')
    # ### end Alembic commands ###
